import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import storybook from 'eslint-plugin-storybook'

export default tseslint.config(
    // `.react-router` is generated by `react-router typegen` and `build` is the
    // compiled output; neither is ours to lint.
    {
        ignores: [
            'dist',
            'build',
            '.react-router',
            '.wrangler',
            'storybook-static',
        ],
    },
    {
        extends: [js.configs.recommended, ...tseslint.configs.strictTypeChecked],
        files: ['**/*.{ts,tsx}'],
        languageOptions: {
            ecmaVersion: 2022,
            globals: globals.browser,
            parserOptions: {
                projectService: true,
                tsconfigRootDir: import.meta.dirname,
            },
        },
        plugins: {
            'react-hooks': reactHooks,
            'react-refresh': reactRefresh,
        },
        rules: {
            ...reactHooks.configs.recommended.rules,
            'react-refresh/only-export-components': [
                'warn',
                { allowConstantExport: true },
            ],
            '@typescript-eslint/no-unused-vars': [
                'error',
                { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
            ],
            '@typescript-eslint/consistent-type-imports': [
                'error',
                { prefer: 'type-imports' },
            ],
        },
    },
    {
        // React Router route modules export `loader`, `meta`, `links` and
        // `headers` alongside the component by design, and they signal 404s
        // with `throw new Response(...)` rather than an Error subclass.
        files: ['src/routes/**/*.tsx', 'src/root.tsx'],
        rules: {
            'react-refresh/only-export-components': 'off',
            '@typescript-eslint/only-throw-error': [
                'error',
                { allow: [{ from: 'lib', name: 'Response' }] },
            ],
        },
    },
    ...storybook.configs['flat/recommended']
)
